  
version: '3.8'

services: 
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: khoahoc
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      # - ./db/backup/files/:/data_backup/data
      # - ./database/khoahoc.sql:/docker-entrypoint-initdb.d/khoahoc.sql
    networks:
      - my-app
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server
    depends_on:
      - db
    links:
      - db
    networks:
      - my-app
    ports:
      - 5000:5000
    # environment:
    #   DB_HOST: mysqldb
    #   DB_USER: root
    #   DB_PASSWORD: 123123
    #   DB_DATABASE: khoahoc
    #   DB_PORT: 3306
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data:
networks:
  my-app:
    driver: bridge
